import{i as u,S as m}from"./assets/vendor-5b791d57.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const c=document.querySelector(".form"),l=document.querySelector(".gallery"),p=document.querySelector("input"),d=document.querySelector(".container"),f=()=>{const r=document.createElement("span");r.classList.add("loader"),d.append(r)},g=()=>{const r=document.querySelector(".loader");r&&r.remove()};c.addEventListener("submit",r=>{f(),r.preventDefault(),l.innerHTML="";const i="42261083-50fe706ca9c2c1734499a9937",a=p.value;fetch(`https://pixabay.com/api/?key=${i}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()}).then(o=>{if(o.hits.length===0)u.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!"});else{let e="";for(let n=0;n<o.hits.length;n++){const s=o.hits[n];e+=`<li class="gallery-item">
    <a href="${s.largeImageURL}">
      <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
    </a>
    <p><b>Likes: </b>${s.likes}</p>
    <p><b>Views: </b>${s.views}</p>
    <p><b>Comments: </b>${s.comments}</p>
    <p><b>Downloads: </b>${s.downloads}</p>
  </li>`}l.insertAdjacentHTML("afterbegin",e);const t=new m(".gallery a",h);t.on("show.simplelightbox"),t.refresh(),c.reset()}}).catch(o=>{console.log(o)}).finally(()=>{g()})});const h={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250};
//# sourceMappingURL=commonHelpers.js.map
